# Generated by Django 5.2.7 on 2025-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_remove_post_user_post_author_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
