# Generated by Django 5.2.7 on 2025-12-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_alter_post_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='post_file/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
