# Generated by Django 5.2.7 on 2025-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_post_author_alter_post_post_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='post_file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
    ]
